n71124/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from hangar.views import SensorReportingView, FrontPageView, SwitchStatusView, ScheduleView
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sensors/', SensorReportingView.as_view()),
    url(r'^switches/', SwitchStatusView.as_view()),
    url(r'^schedule/', login_required(ScheduleView.as_view())),
    url(r'^robots\.txt/$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^$', FrontPageView.as_view()),
]

hangar/forms.py
from django import forms

class SensorForm(forms.Form):
    serial = forms.CharField(max_length=60)
    value = forms.DecimalField(max_digits=5, decimal_places=2)


class SwitchStatusForm(forms.Form):
    serial = forms.CharField(max_length=60)


class ScheduleForm(forms.Form):
    departure = forms.DateTimeField()
    comment = forms.CharField(max_length=255, required=False)
    heater_on = forms.DateTimeField()
    heater_off = forms.DateTimeField()

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>&#9992; N71124 - 1969 Cessna 182</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.23.0/css/uikit.min.css" />
        <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.23.0/js/uikit.min.js"></script>
        <link rel="stylesheet" href="/static/style.css" />
        <link rel="stylesheet" href="/static/n71124.css" />
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        <script type="text/javascript" src="/static/dateformat.js"></script>
    </head>
    <body>
        <nav class="uk-navbar uk-margin-bottom">
            <ul class="uk-navbar-nav">
                <a href="/" class="uk-navbar-brand uk-text-large uk-text-bold">&#9992; N71124</a>
            </ul>
            <div class="uk-navbar-flip">
                <ul class="uk-navbar-nav">
                    <li><a href="/schedule">Manage</a></li>
                </ul>
            </div>
        </nav>
        
        {% block content %}
        
        <script type="text/javascript">
        ambient_dates = {{ ambient_dates|safe }};
        ambient_data = {{ ambient_data|safe }};
        cowling_dates = {{ cowling_dates|safe }};
        cowling_data = {{ cowling_data|safe }};
        </script>
        <script src="/static/chart.js"></script>

        <div class="container">
          <div class="uk-grid">
            <div class="uk-width-medium-1-1">
                <div class="uk-panel uk-panel-box uk-panel-space uk-text-center no-margin">
                    
                    <div class="floater">
                        {% if status %}
                        <button onclick="window.location='/schedule';" class="uk-button uk-button-large uk-button-success uk-align-center" type="button">Heater ON</button>
                        {% else %}
                        <button onclick="window.location='/schedule';" class="uk-button uk-button-large uk-button-danger uk-align-center" type="button">Heater OFF</button>
                        {% endif %}
                        <p>Cowl: {{ cowling }}&deg;F</p>
                        <p>Ambient: {{ ambient }}&deg;F</p>
                        <p>{{ heater_watts }} W,  {{ heater_amps }} A</p>
                    </div>
                    <div id="chart"></div>
                </div>
            </div>
          </div>
        </div>
        {% endblock %}
    </body>
</html>

templates/schedule.html
{% extends "base.html" %}
{% block content %}

<script type="text/javascript">

$(document).ready(function() { 
    $('#id_departure').change(function() {
        d = new Date($(this).val());

        on = new Date(d.getTime() - 8*60*60*1000);
        off =  new Date(d.getTime() + 2*60*60*1000);
        $('#id_heater_on').val(dateFormat(on, "isoDateTime"));
        $('#id_heater_off').val(dateFormat(off, "isoDateTime"));
    });

});
</script>


        <div class="container">
          <div class="uk-grid">
            <div class="uk-width-medium-1-1">
                <div class="uk-panel uk-panel-box uk-panel-space uk-text-center">
<h2>Schedule Heater</h2>

<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Schedule Heater" />
</form>

                </div>
            </div>

            <div class="uk-width-medium-1-1">
                <div class="uk-panel uk-panel-box uk-panel-space uk-text-center">
<h2>Heater Calendar</h2>

{% for s in schedule %}
<p>{{ s }} ( delete )</p>
{% endfor %}

                </div>
            </div>
          </div>
        </div>


{% endblock %}